/**
 * Standardized Error Codes
 * Used across the application for consistent error handling
 */

export const ERROR_CODES = {
  // General errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  
  // Authentication & Authorization
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  
  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  
  // Workspace errors
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_LIMIT_REACHED: 'WORKSPACE_LIMIT_REACHED',
  NOT_WORKSPACE_MEMBER: 'NOT_WORKSPACE_MEMBER',
  INVALID_WORKSPACE_ROLE: 'INVALID_WORKSPACE_ROLE',
  WORKSPACE_INVITE_EXPIRED: 'WORKSPACE_INVITE_EXPIRED',
  
  // Contact errors
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  DUPLICATE_CONTACT: 'DUPLICATE_CONTACT',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  
  // Deal errors
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  INVALID_DEAL_STAGE: 'INVALID_DEAL_STAGE',
  
  // Label errors
  LABEL_NOT_FOUND: 'LABEL_NOT_FOUND',
  DUPLICATE_LABEL: 'DUPLICATE_LABEL',
  
  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  INVALID_TASK_STATUS: 'INVALID_TASK_STATUS',
  
  // Campaign errors
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_ALREADY_STARTED: 'CAMPAIGN_ALREADY_STARTED',
  CAMPAIGN_NOT_RUNNING: 'CAMPAIGN_NOT_RUNNING',
  INVALID_CAMPAIGN_STATUS: 'INVALID_CAMPAIGN_STATUS',
  
  // Message errors
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  
  // License & Credits
  LICENSE_NOT_FOUND: 'LICENSE_NOT_FOUND',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  LICENSE_INVALID: 'LICENSE_INVALID',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  TOPUP_CODE_INVALID: 'TOPUP_CODE_INVALID',
  TOPUP_CODE_USED: 'TOPUP_CODE_USED',
  
  // Billing errors
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  
  // Webhook errors
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  
  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  
  // External services
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  STRIPE_ERROR: 'STRIPE_ERROR',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR',
  
  // Import/Export
  IMPORT_FAILED: 'IMPORT_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

export default { ERROR_CODES, HTTP_STATUS };
